# Config file for HexNicks by Majekdor | Have questions? Ask here: https://discord.majek.dev
# For colors this config uses MiniMessage (https://docs.adventure.kyori.net/minimessage.html#the-components)

# Whether nicknames should show in the tab list
tab-nicks: false

# The maximum number of characters (excluding color codes) a nickname may be
max-length: 20

# The minimum number of characters (excluding color codes) a nickname may be
min-length: 3

# Whether nicknames must be alphanumeric - Regex: [a-zA-Z0-9]+
require-alphanumeric: true

# The plugin needs a chat formatter for nicknames to format properly in chat
# PaperNicks can do this itself but if you have another formatter such as EssentialsChat or VaultChatFormatter you should disable this
chat-formatter: true

# The format of chat messages. Must include {displayname} and {message} placeholders.
# May also include {prefix} and {suffix} placeholders. These items will be pulled from Vault if it is hooked.
chat-format: "<{displayname}> {message}"

# Whether to support legacy nicknames (&a, &l, etc.)
legacy-colors: false

# The default color of nicknames if no color code is provided on nickname creation.
# This MUST be a hex code string. No color names or legacy codes.
default-nick-color: "#FFFFFF"

# The default color of usernames for users without nicknames.
# This MUST be a hex code string. No color names or legacy codes.
default-username-color: "#FFFFFF"

# Whether to send opped players messages when the plugin has an update.
update-prompt: true

# Whether to set a user's Essentials nickname on /nick to fix some Essentials compatibility.
override-essentials: true

# Disabled text decorations for nicknames.
# Accepted values: italic, bold, strikethrough, obfuscated, underlined
disabled-decorations:
  - "example (replace this)"

# Database settings
# Only enable this if you know what you're doing and have an existing database
database-enabled: false
host: ''
port: ''
database: ''
username: ''
password: ''
use-ssl: false
# This is the time, in seconds, for how often the plugin should check the database for updated nicknames.
update-interval: 300

# This should only be enabled if the developer needs additional information about plugin issues
debug: false


# Message configuration
messages:
  invalidSender: "<red>You must be in-game to use this command."
  unknownPlayer: "<red>Unknown player %player%."
  noPermission: "<red>You do not have permission to execute this command."
  tooShort: "<red>That nickname is too short. Minimum length is %length% characters."
  tooLong: "<red>That nickname is too long. Maximum length is %length% characters."
  nonAlphanumeric: "<red>Your nickname must be alphanumeric."
  nicknameSet: "<gray>Your nickname has been set to: <white>%nick%<gray>."
  nicknameSetOther: "<aqua>%player%<gray>'s nickname has been set to: <white>%nick%<gray>."
  nicknameRemoved: "<gray>Nickname removed."
  nicknameRemovedOther: "<aqua>%player%<gray>'s nickname removed."
  onlyColorCodes: "<red>You may only include color codes."
  pluginReloaded: "<green>Plugin reloaded."
  realname: "%nickname% <gray>is <aqua>%name%<gray>."
  update: "<gray>HexNicks has an update! View <click:open_url:https://www.spigotmc.org/resources/83554/><aqua>here</aqua></click>."